show_description: 
  default: true
  description: 'Show description from "About This Category" post'

show_mobile: 
  default: true
  description: 'Show banners on mobile'

show_subcat: 
  default: true
  description: 'Show banners for subcategories'

show_nodesc: 
  default: false
  description: 'Hide banners if description is not set'

exceptions:
  default: ""
  type: list
  description: "Banner will not show for these categories"
